### ISSUE TITLE
Can't type pipe (|) character using a Spanish keyboard

### ISSUE THREAD

**Issue by guillermooo** [wuub/SublimePTY#12]
Need to doublecheck, but I think this is the case for any input that requires pressing AltGr.

**Comment by wuub** [comment]
It would be great if you could take a look and see why 
`{"keys": ["|"], "command": "sublimepty_keypress", "args": {"key": "|", "alt": false, "ctrl": false, "shift": false, "super": false}, "context": [{"key": "setting.sublimepty"}]}` doesn't fire.
`sublime.log_commands(True)` 
should help. Actually testing if keybindings work AND trying to find a workaround when the don't would be a superb contribution, especially since you're using a different locale. 

EDIT: AFAIK to be completely safe it would be best to  bind all [RL][SHIFT|ALT|CTRL], but i Don't think it's possible in sublime.

**Comment by guillermooo** [comment]
I'll find some time to try this out, but just to avoid duplicate work: Do you know whether this is related to virtual-key codes and friends?

BTW, `sublimepty_keypress` is being called correctly, but the modifiers are ignored for the final input, so what ends up in the console buffer is the unshifted char value for the key.

**Comment by wuub** [comment]
If sublime_keypress binding fires correctly, then the problem must be connected with KEY_EVENT_RECORD and win32_keymap.py/make_input_key()

In the past looking at conque (http://conque.googlecode.com/svn-history/r324/branches/windows/autoload/ConqueSoleSubprocess.py) and http://msdn.microsoft.com/en-us/library/ms684166(v=vs.85) helped a lot.
